# Generated by Django 4.2.5 on 2023-09-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Author_Name',
            new_name='Content',
        ),
    ]
