# Generated by Django 4.2.5 on 2023-09-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_blog_end_date_remove_blog_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='BlogId',
            field=models.BigIntegerField(),
        ),
    ]
